In [3]:
import numpy as np

In [ ]:
x = np.arange(10)

x[::-1]  # all elements, reversed
x[::2]  # every other element
x[1::2]  # every other element, starting at index 1

In [10]:
# 2d indexing
x2 = np.random.randint(10, size=(3, 4)) 

print(x2)

x2[::-1, :] #reverse outer, (or leftmost/higher dimension)
x2[:, ::-1] #reverse inner

x2_sub = x2[:2, :2] #modifying subarrays changes the underlying array
x2_sub[0, 0] = 99
print(x2_sub)
print(x2)
x2_sub_copy = x2[:2, :2].copy() #safe way to create a copy and not alter the original

x = np.random.randint(10,size=(3))
# reshaping can be done with .reshape or .newaxis
x.reshape((1, 3)) # equivalent: x[np.newaxis, :]
x.reshape((3, 1)) # equivalent: x[:, np.newaxis]

[[4 9 5 2]
 [0 3 2 2]
 [2 5 1 6]]
[[99  9]
 [ 0  3]]
[[99  9  5  2]
 [ 0  3  2  2]
 [ 2  5  1  6]]


array([[5],
       [2],
       [0]])

In [50]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6],
                 ])
grid2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
np.concatenate([grid, grid2], axis=0) #concat the outermost arrays  must have a matching size per element
# concatenate along the second axis (zero-indexed)
#np.concatenate([grid, grid], axis=1) concat the lower dimension arrays within the outer arrays.  must have a matching number of elements and sizes

x = [1, 2, 3, 9, 7, 3, 2, 1, 7, 6]  #np.split to split into uneven arrays. otherwise reshape will do
x1, x2, x3 = np.split(x, [3, 7])
print(x1, x2, x3)
x1, x2, x3 = np.split(x, [5, 7])
print(x1, x2, x3)


y = np.empty(5) ## empty means uninitialised!!!

y = np.zeros(20)
np.power(2, x, out=y[::2]) ## combining ufuncs and array views example

np.add.reduce(x) # sum
np.add.accumulate(x) # every step til sum
np.multiply.reduce(x) # product
np.multiply.accumulate(x) # every step til product

x = np.arange(1, 6)
np.multiply.outer(x, x) ## ufunc multiplication table       !?

[1 2 3] [9 7 3 2] [1 7 6]
[1 2 3 9 7] [3 2] [1 7 6]


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])